### PR TITLE
fix: add package.json as named export

### PR DESCRIPTION
**Pull request by saibotsivad**
Not a huge priority, but Rollup (specifically the Svelte plugin) keeps complaining because I'm using it in a Svelte component and it can't introspect to see if it can be optimized.

### CODE REVIEW

**Comment by TehShrike** [comment]
does this mean I have to do a feature version bump if I change my npm keywords in the package.json? 😅

**Comment by saibotsivad** [comment]
Not at all!

The semver bump is entirely dependent on change files (the frontmatter markdown files in the `.changeset` folder, which means:

1. No files? No semver bump.

You could introduce a minor spelling fix, or a major breaking change, but if it's not documented in a change file changeset wouldn't know or do anything.

2. Wrong semver bump? Just update the files on the main branch.

The changeset-bot opens a PR for release, like [this example](https://github.com/tobiaslabs/hunch/pull/22/files), so you can always verify what the bump will be prior to release.

If the PR for the release showed an incorrect semver bump, you just update the change files on the main branch until it's right.

---

So in the case of wanting to fiddle with the npm keywords in the `package.json`, you might decide:

- If you don't want *any* npm release, like if you'll wait and push it out with the next "real" release, just don't add a change file.
- If you want to push it out to npm now, make a change file with a `patch`, like [this commit example](https://github.com/tobiaslabs/hunch/commit/59109168386772a8689c2efeb6440b7955de8d5e).

**Comment by saibotsivad** [comment]
For small projects like we have, you probably only have one or two files per release, so it's pretty easy to manage.

Bigger projects may end up with lots and lots of change files (one per PR with a different name to avoid merge conflicts) so then you can use the cli tool to merge the change files into one file, or manually edit them, or whatever.

Just remember that what changeset-bot **proposes** (the release PR) is based on whatever change files are in the current head, and after that it's pretty straightforward.

**Comment by saibotsivad** [comment]
Personally I would think of it as a ~patch: when you added the named `exports` in [85fb8bd](https://github.com/TehShrike/financial-number/commit/85fb8bd6ec24fcf7a053b67a1f9032652c0b57c6#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R7) you "should have" included `./package.json` as a named export but didn't realize. 🤷‍♂️

**Comment by TehShrike** [comment]
Published as 4.0.3

**Pull request merged**
